from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.agents.data_cleaner import DataCleanerAgent
from src.agents.feature_engineer import FeatureEngineerAgent
from src.agents.model_trainer import ModelTrainerAgent
from src.config import (
    AGENT_LOG_PATH,
    CLEAN_DATA_PATH,
    CLEANER_REPORT_PATH,
    ENGINEER_REPORT_PATH,
    ENGINEERED_DATA_PATH,
    FINAL_REPORT_PATH,
    RAW_DATA_PATH,
    TRAINER_REPORT_PATH,
    ensure_dirs,
)
from src.context import PipelineContext
from src.logging_utils import AgentLogger
from src.structured_report import StructuredReport, save_report


def _shape(path: Path) -> str:
    if not path.exists():
        return "N/A"
    df = pd.read_csv(path)
    return f"{df.shape[0]} rows × {df.shape[1]} columns"


def _report_section(report: StructuredReport | None) -> str:
    if report is None:
        return "_No structured report available._"
    return f"{report.narrative()}\n\n**Structured JSON:**\n\n```json\n{report.to_json()}\n```"


def write_final_report(ctx: PipelineContext, logger: AgentLogger) -> None:
    metrics = ctx.training_metrics or {}
    metrics_lines = (
        "\n".join(f"- **{k}**: {v:.4f}" for k, v in metrics.items())
        or "- (no metrics parsed from training stdout)"
    )

    report = f"""# Multi-Agent AutoML — Final Report

## Pipeline Overview

| Stage | Artifact | Shape | Structured Report |
|-------|----------|-------|-------------------|
| Raw | `{RAW_DATA_PATH.name}` | {_shape(RAW_DATA_PATH)} | — |
| Cleaned | `{CLEAN_DATA_PATH.name}` | {_shape(CLEAN_DATA_PATH)} | `{CLEANER_REPORT_PATH.name}` |
| Engineered | `{ENGINEERED_DATA_PATH.name}` | {_shape(ENGINEERED_DATA_PATH)} | `{ENGINEER_REPORT_PATH.name}` |
| Model | XGBoost | — | `{TRAINER_REPORT_PATH.name}` |

## Agent 1 — Data Cleaner

{_report_section(ctx.cleaner_report)}

## Agent 2 — Feature Engineer

{_report_section(ctx.engineer_report)}

## Agent 3 — Model Trainer

{_report_section(ctx.trainer_report)}

### Final Model Metrics

{metrics_lines}

### Training Iterations

The model trainer executed **{len(ctx.training_code_history)}** script(s) during the feedback loop.

## Execution Logs

Full agent conversation log: `{AGENT_LOG_PATH.name}`

---
*Generated by the Multi-Agent AutoML Team pipeline.*
"""
    FINAL_REPORT_PATH.write_text(report, encoding="utf-8")
    logger.log("SYSTEM", f"Final report written to {FINAL_REPORT_PATH}")


class Orchestrator:
    def __init__(self) -> None:
        ensure_dirs()
        self.logger = AgentLogger()
        self.ctx = PipelineContext()

    def run(self) -> None:
        if not RAW_DATA_PATH.exists():
            raise FileNotFoundError(
                f"Missing {RAW_DATA_PATH}. Run: python scripts/prepare_sample_data.py"
            )

        self.logger.section("Multi-Agent AutoML Pipeline")

        cleaner = DataCleanerAgent(self.ctx, self.logger)
        self.ctx.cleaner_report = cleaner.run()
        save_report(self.ctx.cleaner_report, CLEANER_REPORT_PATH)
        if not CLEAN_DATA_PATH.exists():
            raise RuntimeError("Agent 1 did not save clean_data.csv. Check agent logs.")

        engineer = FeatureEngineerAgent(self.ctx, self.logger)
        self.ctx.engineer_report = engineer.run()
        save_report(self.ctx.engineer_report, ENGINEER_REPORT_PATH)
        if not ENGINEERED_DATA_PATH.exists():
            raise RuntimeError("Agent 2 did not save engineered_data.csv. Check agent logs.")

        trainer = ModelTrainerAgent(self.ctx, self.logger)
        self.ctx.trainer_report = trainer.run()
        save_report(self.ctx.trainer_report, TRAINER_REPORT_PATH)

        write_final_report(self.ctx, self.logger)
        self.logger.section("Pipeline complete")
